### PR TITLE
Endpoint returning number of cases with SNVs and SVs

### PR DESCRIPTION
**Pull request by northwestwitch**
### This PR adds | fixes:
- Adds the `cases` endpoint, which returns the number of cases with SNVs and SVs. 

Added this because it's required in scout, specifically [here](https://github.com/Clinical-Genomics/scout/blob/dfec1c0c670c15f7e4babad75cf7a1261870c374/scout/server/blueprints/variant/controllers.py#L296)

**How to prepare for test**:
- [ ] remove any previous Docker image for this repo: `docker image rm loqusdbapi_loqusdbapi`
- [ ] run `docker compose up`

### How to test:
- Send a get request to the server from another terminal: 
```curl -X GET "http://127.0.0.1:9000/cases"```

-  run `docker compose down`

### Expected outcome:
- The endpoint should return number of cases in database with SNVs and with SVs

### Review:
- [ ] Code approved by
- [x] Tests executed by CR
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Tested:

image

**Review by moonso — APPROVED** [review]
👍

**Comment by northwestwitch** [comment]
Thanks @moonso!

**Comment by moonso** [comment]
Thanks to you @northwestwitch for making the PRs and not just ask me to do it!!!

**Comment by northwestwitch** [comment]
> Thanks to you @northwestwitch for making the PRs and not just ask me to do it!!!

But if I ask you, you might use the evergreen answer : feel free to open a PR to fix it!  🤣

**Pull request merged**
