### PR TITLE
Push image to Docker Hub prod and stage

### LINKED ISSUE #9: Add the image of this repo to Docker hub
Via a github action perhaps? This was a request originally from Lund

### PR DESCRIPTION
**Pull request by northwestwitch**
### This PR adds | fixes: fix #9 
- Github action triggered:
- Push images with tags: version_nr, latest to clinicalgenomics/loqusdbapi when a new release is published
- Push images with tags: branch_name, latest to clinicalgenomics/loqusdbapi-stage on push events

### Review:
- [ ] Code approved by
- [x] Tests executed by github actions
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Hi @moonso we'd like to deploy and use this repo on the server farm, after moving the LoqusDB database there as well. Eventually Scout would connect to Loqus using this API instead of the command line. To use it via podman and systemd we need to pull it from Docker Hub. This PR should do the pushing to Docker Hub every time we merge a PR to master!

**Comment by northwestwitch** [comment]
Pushed to Docker hub on push event: 🆗 

image

**Comment by Mropat** [comment]
Nice! We talked about using official action, and I will have to change this for statina and cg in the future, but [this was useful anyway](https://docs.docker.com/ci-cd/github-actions/)

**Comment by Mropat** [comment]
Someone has to log in as clinicalgenomics and add a deploy key if it doesnt exist yet

**Comment by northwestwitch** [comment]
> Nice! We talked about using official action, and I will have to change this for statina and cg in the future, but [this was useful anyway](https://docs.docker.com/ci-cd/github-actions/)

What's the official action?

**Comment by northwestwitch** [comment]
> > Nice! We talked about using official action, and I will have to change this for statina and cg in the future, but [this was useful anyway](https://docs.docker.com/ci-cd/github-actions/)
> 
> What's the official action?

Ah OK this one: docker/build-push-action@v2

**Comment by northwestwitch** [comment]
Now @Mropat ?

**Review by Mropat — APPROVED** [review]
Awesome!!

**Comment by henrikstranneheim** [comment]
Well done!

**Comment by northwestwitch** [comment]
The action to push to to Docker Hub (prod image) wasn't triggered by the new release. We've been missing something.. 🤔

**Pull request merged**
